"""add firmware file fields

Revision ID: 0f174eb7bad3
Revises: 20260302_0001
Create Date: 2026-03-03 16:38:53.000453+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '0f174eb7bad3'
down_revision: Union[str, None] = '20260302_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware_upgrades',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('previous_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('target_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('firmware_file_path', sa.Text(), nullable=True),
    sa.Column('firmware_file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmware_upgrades_device_id'), 'firmware_upgrades', ['device_id'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('device_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sections', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('delivery_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syslog_entries',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('facility', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('program', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syslog_entries_device_id'), 'syslog_entries', ['device_id'], unique=False)
    op.create_index(op.f('ix_syslog_entries_received_at'), 'syslog_entries', ['received_at'], unique=False)
    op.create_index(op.f('ix_syslog_entries_source_ip'), 'syslog_entries', ['source_ip'], unique=False)
    op.create_table('vpn_tunnels',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tunnel_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('tunnel_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('remote_gateway', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('local_subnet', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('remote_subnet', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'tunnel_name', name='uq_vpn_device_tunnel')
    )
    op.create_index(op.f('ix_vpn_tunnels_device_id'), 'vpn_tunnels', ['device_id'], unique=False)
    op.alter_column('alert_deliveries', 'payload_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text"))
    op.alter_column('alert_deliveries', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('alert_deliveries_rule_id_fkey', 'alert_deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'alert_deliveries', 'alert_rules', ['rule_id'], ['id'])
    op.alter_column('alert_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('api_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('api_tokens_user_id_fkey', 'api_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'api_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('compliance_results', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('compliance_results_rule_id_fkey', 'compliance_results', type_='foreignkey')
    op.drop_constraint('compliance_results_device_id_fkey', 'compliance_results', type_='foreignkey')
    op.create_foreign_key(None, 'compliance_results', 'compliance_rules', ['rule_id'], ['id'])
    op.create_foreign_key(None, 'compliance_results', 'devices', ['device_id'], ['id'])
    op.alter_column('compliance_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('config_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('config_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('config_templates_name_key', 'config_templates', type_='unique')
    op.drop_index('ix_config_templates_name', table_name='config_templates')
    op.create_index(op.f('ix_config_templates_name'), 'config_templates', ['name'], unique=True)
    op.drop_constraint('device_backup_settings_device_id_fkey', 'device_backup_settings', type_='foreignkey')
    op.create_foreign_key(None, 'device_backup_settings', 'devices', ['device_id'], ['id'])
    op.alter_column('device_metrics', 'uptime_seconds',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('device_metrics', 'collected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_device_metrics_collected_at', table_name='device_metrics')
    op.drop_constraint('device_metrics_device_id_fkey', 'device_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'device_metrics', 'devices', ['device_id'], ['id'])
    op.alter_column('device_risk_scores', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_device_risk_scores_calculated_at', table_name='device_risk_scores')
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('security_finding_exclusions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('security_findings', 'remediation_patch',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('security_findings', 'first_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('security_findings', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_security_findings_scan_id', table_name='security_findings')
    op.drop_index('ix_security_findings_severity', table_name='security_findings')
    op.drop_index('ix_security_findings_status', table_name='security_findings')
    op.alter_column('security_scans', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_scans', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_security_findings_status', 'security_findings', ['status'], unique=False)
    op.create_index('ix_security_findings_severity', 'security_findings', ['severity'], unique=False)
    op.create_index('ix_security_findings_scan_id', 'security_findings', ['scan_id'], unique=False)
    op.alter_column('security_findings', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('security_findings', 'first_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('security_findings', 'remediation_patch',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('security_finding_exclusions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_device_risk_scores_calculated_at', 'device_risk_scores', ['calculated_at'], unique=False)
    op.alter_column('device_risk_scores', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'device_metrics', type_='foreignkey')
    op.create_foreign_key('device_metrics_device_id_fkey', 'device_metrics', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_device_metrics_collected_at', 'device_metrics', ['collected_at'], unique=False)
    op.alter_column('device_metrics', 'collected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('device_metrics', 'uptime_seconds',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(None, 'device_backup_settings', type_='foreignkey')
    op.create_foreign_key('device_backup_settings_device_id_fkey', 'device_backup_settings', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_config_templates_name'), table_name='config_templates')
    op.create_index('ix_config_templates_name', 'config_templates', ['name'], unique=False)
    op.create_unique_constraint('config_templates_name_key', 'config_templates', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('config_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('config_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('compliance_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'compliance_results', type_='foreignkey')
    op.drop_constraint(None, 'compliance_results', type_='foreignkey')
    op.create_foreign_key('compliance_results_device_id_fkey', 'compliance_results', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('compliance_results_rule_id_fkey', 'compliance_results', 'compliance_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.alter_column('compliance_results', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'api_tokens', type_='foreignkey')
    op.create_foreign_key('api_tokens_user_id_fkey', 'api_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('api_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('alert_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'alert_deliveries', type_='foreignkey')
    op.create_foreign_key('alert_deliveries_rule_id_fkey', 'alert_deliveries', 'alert_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.alter_column('alert_deliveries', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('alert_deliveries', 'payload_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text"))
    op.drop_index(op.f('ix_vpn_tunnels_device_id'), table_name='vpn_tunnels')
    op.drop_table('vpn_tunnels')
    op.drop_index(op.f('ix_syslog_entries_source_ip'), table_name='syslog_entries')
    op.drop_index(op.f('ix_syslog_entries_received_at'), table_name='syslog_entries')
    op.drop_index(op.f('ix_syslog_entries_device_id'), table_name='syslog_entries')
    op.drop_table('syslog_entries')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_firmware_upgrades_device_id'), table_name='firmware_upgrades')
    op.drop_table('firmware_upgrades')
    # ### end Alembic commands ###
